import React, { Component } from 'react'
import Sidebar from '../Comp/Sidebar.tsx'

export default class Explore extends Component {
  render() {
    return (
      <div className='flex '>
      <Sidebar/>
      <div>
      <div className='max-h-[100vh] overflow-y-auto '>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      <h1>hdaqidw</h1>
      </div>
      
      </div>
     
    </div>
    )
  }
}
